FROM python:3.11-slim

ENV PYTHONUNBUFFERED 1
WORKDIR /api
# COPY . /api
COPY requirements.txt /api/

RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

CMD ["python", "api.py"]